<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <?php include_once($this->url_root."view/include/head_tags.phtml"); ?>

    <link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/cadastro.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/general.css">
  </head>

  <body>

    <?php include_once($this->url_root."view/include/navigation.phtml"); ?>

    <script src="<?php echo $this->url_root ?>view/js/navbar.js"></script>
  </body>
</html>