<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <?php include_once("view/include/head_tags.phtml"); ?>

    <link rel="stylesheet" type="text/css" href="view/css/login.css">
    <link rel="stylesheet" type="text/css" href="view/css/general.css">
  </head>

  <body>

    <?php include_once("view/include/navigation.phtml"); ?>

    <br>

    <div class="container">
      <div class="columns is-vcentered">
        <div class="column">
          <div class="content">
            <h1 class="title">
              <?php
                echo ucfirst($this->titulo) . " " . $this->codigo;
              ?>
            </h1>
            <p class="is-size-4""><?php echo $this->mensagem ?></p>
          </div>
        </div>
      </div>
    </div>

    <script src="view/js/navbar.js"></script>
  </body>
</html>