<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <?php include_once($this->url_root . "view/include/head_tags.phtml"); ?>

    <link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/login.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/general.css">
  </head>

  <body>

    <?php include_once($this->url_root . "view/include/navigation.phtml"); ?>

    <br>
    <div class="container">
      <div class="columns is-vcentered">
        <div class="column">
          <h1 class="title is-1">Login</h1>
          <p>
            Faça login com sua conta da SeTAC² e acesse todas as informações sobre a edição atual do evento!
          </p>
        </div>
        <div class="column">
          <div class="box">
            <div class="logo-setac">
              <img src="view/img/logo.png" alt="Logo da SeTAC²">
            </div>
            <form class="form" action="controller/Authentication.php" method="post">
              <div class="field">
                <label for="usuario" class="label">Usuário</label>
                <div class="control">
                  <input type="text" name="usuario" class="input" required>
                </div>
              </div>
              <div class="field">
                <label for="senha" class="label">Senha</label>
                <div class="control">
                  <input type="password" name="senha" class="input" required>
                </div>
              </div>
              <div class="field is-grouped">
                <div class="control">
                  <input type="submit" value="Entrar" class="button is-info has-text-weight-bold">
                </div>
                <div class="control">
                  <a href="" class="button is-text">Recuperar dados</a>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script src="<?php echo $this->url_root ?>view/js/navbar.js"></script>
  </body>
</html>