<?php include "view/include/title_config.phtml"; ?>

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <?php include "view/include/head_tags.phtml"; ?>

    <link rel="stylesheet" type="text/css" href="view/css/cadastro.css">
    <link rel="stylesheet" type="text/css" href="view/css/general.css">
  </head>

  <body>

    <?php include_once "view/include/navigation.phtml" ?>

    <script src="view/js/navbar.js"></script>
  </body>
</html>