<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Os títulos das páginas são definidos em view/include/title_config.php -->
<title><?php echo "SeTAC² - " . ucfirst($this->titulo); ?></title>

<link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/bulma.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->url_root ?>view/css/general.css">

<script defer src="<?php echo $this->url_root ?>view/js/fontAwesome.js"></script>