<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a href="#" class="navbar-item">
        <h2 class="logo">SeTAC²</h2>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped is-dark">
          <?php if($this->modulo === "") {?>
            <?php if($this->titulo === "erro") {?>
            <a class="button is-link" href="<?php echo $this->url_root ?>login.php">
              <strong>Voltar</strong>
            </a>
            <?php } else {?>
            <p class="control">
            <?php if($this->titulo === "cadastro") {?>
              <a class="button is-link" href="cadastro.php">
                <i class="fas fa-user-plus mr-10"></i>
                <span class="has-text-weight-bold">Cadastrar</span>
              </a>
            <?php } else { ?>
              <a class="button is-dark" href="cadastro.php">
                <i class="fas fa-user-plus mr-10"></i>
                <span>Cadastrar</span>
              </a>
            <?php } ?>
            </p>
            <p class="control">
            <?php if($this->titulo === "login") {?>
              <a class="button is-link" href="login.php">
                <i class="fas fa-sign-in-alt mr-10"></i>
                <span class="has-text-weight-bold">Login</span>
              </a>
            <?php } else { ?>
              <a class="button is-dark" href="login.php">
                <i class="fas fa-sign-in-alt mr-10"></i>
                <span>Login</span>
              </a>
            <?php } ?>
            </p>
          <?php }} else if($this->modulo === "painel") {?>
            <p class="control">
              <a class="button is-dark" href="<?php echo $this->url_root ?>painel">
                <i class="fas fa-user mr-10"></i>
                <span>
                  <?php echo $this->usuario->getLogin(); ?>
                </span>
              </a>
            </p>
            <p class="control">
              <a class="button is-link" href="<?php echo $this->url_root ?>logout.php">
                <i class="fas fa-sign-out-alt mr-10"></i>
                <span class="has-text-weight-bold">Logout</span>
              </a>
            </p>
          <?php } ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>