<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a href="#" class="navbar-item">
        <h2 class="logo">SeTAC²</h2>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped is-dark">
          <?php if($this->titulo === "erro") {?>
            <a class="button is-link" href="login.php">
              <strong>Voltar</strong>
            </a>
          <?php } else {?>
            <p class="control">
            <?php if($this->titulo === "cadastro") {?>
              <a class="button is-link" href="cadastro.php">
                <strong>Cadastro</strong>
              </a>
            <?php } else { ?>
              <a class="button is-light" href="cadastro.php">
                Cadastro
              </a>
            <?php } ?>
            </p>
            <p class="control">
            <?php if($this->titulo === "login") {?>
              <a class="button is-link" href="login.php">
                <strong>Login</strong>
              </a>
            <?php } else { ?>
              <a class="button is-light" href="login.php">
                Login
              </a>
            <?php } ?>
            </p>
          <?php } ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>